/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author "Aizaz"
 * class id= "17150"
 * 
 **/

package student.information.system;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import com.sun.glass.events.KeyEvent;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

public class SignIn extends javax.swing.JFrame {
Connection conn=null;
Connection conn1=null;
ResultSet rs=null;
ResultSet rs1=null;
PreparedStatement pst=null;
PreparedStatement pst1=null;

    /**
     * Creates new form Login
     */
    public SignIn() {
        initComponents();
         conn=Data.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel2.setText("Username :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(380, 250, 70, 14);

        jLabel3.setText("Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(380, 300, 70, 14);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 390, 160, 30);

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username);
        txt_username.setBounds(470, 240, 160, 30);
        jPanel1.add(txt_password);
        txt_password.setBounds(470, 290, 160, 30);

        txt_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Student", "Faculty" }));
        txt_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_comboActionPerformed(evt);
            }
        });
        jPanel1.add(txt_combo);
        txt_combo.setBounds(470, 340, 160, 30);

        jLabel4.setText("Login Type:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 350, 80, 14);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("School Management System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 50, 230, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school-building.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel5.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel5.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 210, 230, 170);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txt_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_comboActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        int count =0;

        String user=txt_username.getText().toString();
        System.out.println(user);
        String sql = "select id,username,password,division from Users Where (username =? and password =? and division =?)";
        if(user.equalsIgnoreCase("aizaz") && txt_password.getText().equalsIgnoreCase("17150") ){

            count =1;
            System.out.println(count);
        }
        try{

            pst=conn.prepareStatement(sql);

            pst.setString(1,txt_username.getText());
            pst.setString(2,txt_password.getText());
            pst.setString(3, txt_combo.getSelectedItem().toString());

            rs=pst.executeQuery();

            {
            }
            if(txt_username.getText().toString()=="aizaz"){
                int id = rs.getInt(1);
                JOptionPane.showMessageDialog(null,"Sucess" );
                Employee.empId = id;
                count =1;
                System.out.println(count);
            }
            String access=(txt_combo.getSelectedItem().toString());

            if(access=="Admin") {

                if(count==1){
                    JOptionPane.showMessageDialog(null,"Sucess" );
                    Home j = new Home();
                    Student_Registeration s=new Student_Registeration();

                    j.setVisible(true);

                    this.dispose();

                    Date currentDate = GregorianCalendar.getInstance().getTime();
                    DateFormat df = DateFormat.getDateInstance();
                    String dateString = df.format(currentDate);

                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                    String timeString = sdf.format(d);

                    String value0 = timeString;
                    String values = dateString;

                    int value = Employee.empId;
                    String reg = "insert into Audit (emp_id,date,status) values ('"+value+"','"+value0+" / "+values+"','Logged in')";
                    pst=conn.prepareStatement(reg);
                    pst.execute();
                    this.dispose();

                }

                else if(count>1){
                    JOptionPane.showMessageDialog(null,"Duplicate Username or Password Access denied");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Username and Password is not correct");
                }
            }
            if(access=="Student"){

                int count1=0;
                conn1=dbfile.java_db();
                String sql1 = "select stdid,stdname,stdpass from aizazstudent Where (stdname =? and stdpass =?)";
                pst1=conn1.prepareStatement(sql1);

                pst1.setString(1,txt_username.getText().toString());
                pst1.setString(2,txt_password.getText());

                rs1=pst1.executeQuery();
                while(rs1.next()){
                    JOptionPane.showMessageDialog(null, "Success");
                    System.err.println(rs1.getInt(1));
                    Student_Form s=new Student_Form(rs1.getInt((1)));

                    s.setVisible(true);
                }

            }

            if(access=="Faculty"){

                int count1=0;
                conn1=dbfile.java_db();
                String sql1 = "select id,facname,facpass from aizazfaculty Where (facname =? and facpass =?)";
                pst1=conn1.prepareStatement(sql1);

                pst1.setString(1,txt_username.getText().toString());
                pst1.setString(2,txt_password.getText());

                rs1=pst1.executeQuery();
                while(rs1.next()){
                    JOptionPane.showMessageDialog(null, "Success");
                    System.err.println(rs1.getInt(1));
                    Faculty s=new Faculty(rs1.getInt((1)));

                    s.setVisible(true);
                }

            }

        } catch(Exception e)

        {
            JOptionPane.showMessageDialog(null, e);

        }

        finally {

            try{
                rs.close();
                pst.close();
                rs1.close();
                pst1.close();

            }
            catch(Exception e){

            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> txt_combo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
